#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-googleapis_common_protos
Version  : 1.54.0
Release  : 19
URL      : https://files.pythonhosted.org/packages/97/94/e55c0151d6665a5ff7305fef38c7e8f1defa4679f884aaf9812fb42a1109/googleapis-common-protos-1.54.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/97/94/e55c0151d6665a5ff7305fef38c7e8f1defa4679f884aaf9812fb42a1109/googleapis-common-protos-1.54.0.tar.gz
Summary  : Common protobufs used in Google APIs
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-googleapis_common_protos-license = %{version}-%{release}
Requires: pypi-googleapis_common_protos-python = %{version}-%{release}
Requires: pypi-googleapis_common_protos-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: googleapis-common-protos
Provides: googleapis-common-protos-python
Provides: googleapis-common-protos-python3
BuildRequires : pypi(protobuf)

%description
# Google APIs common protos
[![pypi](https://img.shields.io/pypi/v/googleapis-common-protos.svg)](https://pypi.org/project/googleapis-common-protos/)

%package license
Summary: license components for the pypi-googleapis_common_protos package.
Group: Default

%description license
license components for the pypi-googleapis_common_protos package.


%package python
Summary: python components for the pypi-googleapis_common_protos package.
Group: Default
Requires: pypi-googleapis_common_protos-python3 = %{version}-%{release}

%description python
python components for the pypi-googleapis_common_protos package.


%package python3
Summary: python3 components for the pypi-googleapis_common_protos package.
Group: Default
Requires: python3-core
Provides: pypi(googleapis_common_protos)
Requires: pypi(protobuf)

%description python3
python3 components for the pypi-googleapis_common_protos package.


%prep
%setup -q -n googleapis-common-protos-1.54.0
cd %{_builddir}/googleapis-common-protos-1.54.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641439172
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-googleapis_common_protos
cp %{_builddir}/googleapis-common-protos-1.54.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-googleapis_common_protos/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-googleapis_common_protos/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
